---
title: "Master document, may become the supp mat if we push this approach of R markdown'ing everything"
author: "Anderson et al"
date: "April 20, 2018"
output: pdf_document
---

<!--Install the correct reumannplatz version from github, i.e., the one current on 2018 04 20, tagged
in git with AndersonDeer-->
```{r rp_install}
library(devtools)
devtools::install_github(repo="reumandc/reumannplatz",ref="AndersonDeer")
```

<!--Libraries. Should use checkpoint, but having trouble using reumannplatz from github and checkpoint
at the same time. To be solved later if possible.-->
```{r libraries}
library(reshape2)
library(tidyr)
library(plyr)
library(tools)
library(fields)
library(Reumannplatz)
library(shape)
```

<!--Flags controlling the run and other setup-->
```{r setup}
#which density to use ("dnr" for original estimates, "tom" for your own calculations)
dens.flag<-"dnr"

#what is the earliest year you want? (hunting only: 1960; abundance: 1981; DVC: 1987; Traffic: 1988, Hunters: 1992)
minyear<-1981

#what is the last year you want? (max is 2016)
maxyear<-2016
  
#normalize the data ("norm" for Box-Cox, "detr" for linearly detrend, or "none")
##Code currently work using the "none" option; the normalization steps happen 
##individually with each analysis step (e.g. see line 15 in "DeerAbundance.R" file), 
##because of the conflicting data lengths and dimensions. 
detr.flag<-"none"

#set spatial scale flag for data generation ("usda", "county" or "both")
scale.flag<-"both"

#***DAN: Not sure what this is, Tom, if this is not necessary should be deleted? 
#calculate how many missing climate values there were (don't need to run anymore)
samplesize.flag<-"n"

#set number of surrogates to use for spatial coherence
nsurrogs<-10000

#a function needed for caching
source("Code/mtime.R") 
```

<!--***DAN: Rum time is sufficiently long that we should probably use caching, but
that will require a good understanding of dependencies of everything. I have begun.
Other reasons to use cacheing include it will enforce a clearer specification of
dependencies between chunks.-->

<!--Clean the population data-->
```{r clean_pop_data, cache=T,cache.extra=list(dens.flag,minyear,maxyear,detr.flag,mtime("Code/wi.deer.cleandata.R"),mtime("Data/State_Kill.csv"),mtime("Data/County_KillTotal.csv"),mtime("Data/County_Kill_BuckOnly.csv"),mtime("Data/County_Kill_DoeOnly.csv"),mtime("Data/County_KillGunBuck.csv"),mtime("Data/County_KillGunDoe.csv"),mtime("Data/County_KillBowBuck.csv"),mtime("Data/County_KillBowDoe.csv"),mtime("Data/WI_Cty_CentroidDD.csv"),mtime("Data/DOT_Accidents1987_2016.csv"),mtime("Data/Adj_DOT_Accidents1987_2016.csv"),mtime("Data/OpeningDay.csv"),mtime("Data/CornHarvest.csv"),mtime("Data/WI_USDA_Sections.csv"),mtime("Data/USDA_centroids.csv"),mtime("Data/Cty_Traffic.csv"),mtime("Data/DMU_DeerAbundance1981_2013.csv"),mtime("Data/DMU_DeerDensity1981_2013.csv"),mtime("Data/DMU_HunterAbundance1975_2013.csv"),mtime("Data/DMU_HunterDensity1975_2013.csv"),mtime("Data/hunterdens1416.csv"),mtime("Data/hunterabun1416.csv"),mtime("Data/Cty_Abun_2014_2016.csv"),mtime("Data/permit_issued1970_2013.csv"))}
#Clean population data: end result are two lists of matrices called "cty.list" and "usda.list"
system.time(source("Code/wi.deer.cleandata.R"))
  #list of files generated by wi.deer.cleandata.R:
    #scale.flag == "usda": usda.list, includes data on abundance, kill data, crops, DVCs and traffic
    #scale.flag == "county": cty.list, includes data on abundance, kill data, crops, DVCs and traffic
```

<!--Clean the climate data-->
```{r clean_clim_data, cache=T, cache.extra=list(minyear,maxyear,detr.flag,scale.flag,mtime("Code/wi_climate.R"),mtime("Data/noaa_latlongUpd.csv"),mtime("Data/WI_USDA_Sections.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set1.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set2.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set3.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set4.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set5.csv"),mtime("Data/Cty_NOAA_Temp1981_2015_set6.csv"),mtime("Data/Cty_NOAA_Temp2016_2017.csv"),mtime("Data/Cty_NOAA_Precip1981_1985.csv"),mtime("Data/Cty_NOAA_Precip1986_1991.csv"),mtime("Data/Cty_NOAA_Precip1992_1997.csv"),mtime("Data/Cty_NOAA_Precip1998_2003.csv"),mtime("Data/Cty_NOAA_Precip2004_2009.csv"),mtime("Data/Cty_NOAA_Precip2010_2015.csv"),mtime("Data/Cty_NOAA_Precip2016_2017.csv"),mtime("Data/climate_indices.csv"),mtime("Data/mei.csv"),mtime("Data/pdo.csv"),mtime("Data/npi.csv"),mtime("Data/ENSO.csv"))}
system.time(source("Code/wi_climate.R"))
#list of files generated by wi_climate.R:
  #scale.flag == "usda": wsi.usda.mat,hunt.clim.usda, winter.clim.usda,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #scale.flag == "county": wsi.mat,wsi.matN,hunt.clim,winter.clim,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #large climate indices are the same values (nao,mei,pdo), just replicated into different dimensions to match scale.flag
```

<!--County analysis-->
```{r county_analysis}
#Run analysis on deer abundance and DVCs using county data
system.time(source("Code/DeerAbundance.R"))
```

<!--***DAN: You want this whole code suite to be *exactly* reproducible, so any random bits
need to have the seed set first. Check for that.-->

<!--District analysis-->
```{r district_analysis}
#Run analysis on deer abundance and DVCs using USDA district data
system.time(source("Code/DeerAbundanceUSDA.R"))
```

<!--Make plots-->
```{r make_plots}
#generate raw data plots
system.time(source("Code/deer_plots.R"))

#***DAN: I got the following warnings when I ran deer_plots.R, we have to get 
#to the bottom of these and make them stop by solving the underlying problem:
#Warning messages:
#  1: In plot.window(...) : "smallplot" is not a graphical parameter
#2: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#3: In title(...) : "smallplot" is not a graphical parameter
#4: In plot.window(...) : "smallplot" is not a graphical parameter
#5: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#6: In title(...) : "smallplot" is not a graphical parameter
#7: In plot.window(...) : "smallplot" is not a graphical parameter
#8: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#9: In title(...) : "smallplot" is not a graphical parameter
#10: In plot.window(...) : "smallplot" is not a graphical parameter
#11: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#12: In title(...) : "smallplot" is not a graphical parameter
#13: In plot.window(...) : "smallplot" is not a graphical parameter
#14: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#15: In title(...) : "smallplot" is not a graphical parameter
#16: In plot.window(...) : "smallplot" is not a graphical parameter
#17: In plot.xy(xy, type, ...) : "smallplot" is not a graphical parameter
#18: In title(...) : "smallplot" is not a graphical parameter

#***DAN: Fig 1 does not appear, the code for it needs to be put in
```