## Wisconsin Deer Hunting-Deer Abundance-DVC Master File
## Author: Tom Anderson

#clear workspace
rm(list=ls())

#load relevant packages
library(reshape2)
library(tools)
library(fields)
library(shape)
library(devtools)
library(wsyn)

#which density to use ("dnr" for original estimates, "tom" for your own calculations)
dens.flag<-"dnr"

#what is the earliest year you want? (hunting only: 1960; abundance: 1981; DVC: 1987; Traffic: 1988, Hunters: 1992)
minyear<-1981

#what is the last year you want? (max is 2016)
maxyear<-2016

#set directory
setwd("C:/Users/Tom/Documents/deer_test/mbsync/AndersDeerShort/")
#setwd("/mnt/hgfs/C/Reuman/gitrepos/mbsync/AndersDeerShort/")

#Clean data: end result are two lists of matrices called "cty.list" and "usda.list"
system.time(source("Code/Deer_DataGeneration.R"))
  #list of files generated by wi.deer.cleandata.R:
    #scale.flag == "usda": usda.list, includes data on abundance, kill data, crops, DVCs and traffic
    #scale.flag == "county": cty.list, includes data on abundance, kill data, crops, DVCs and traffic

system.time(source("Code/Climate_DataGeneration.R"))
#list of files generated by wi_climate.R:
  #scale.flag == "usda": wsi.usda.mat,hunt.clim.usda, winter.clim.usda,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #scale.flag == "county": wsi.mat,wsi.matN,hunt.clim,winter.clim,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #large climate indices are the same values (nao,mei,pdo), just replicated into different dimensions to match scale.flag

#set number of surrogates to use for spatial coherence
nsurrogs<-100

#Run analysis on deer abundance and DVCs using county and/or district data (depending on scale flag)
system.time(source("Code/DeerCoherence_wsyn.R"))

#generate plots
system.time(source("Code/deer_plots.R"))

