## Wisconsin Deer Hunting-Deer Abundance-DVC Master File
## Author: Tom Anderson

#clear workspace
rm(list=ls())

#load relevant packages
library(reshape2)
library(tidyr)
library(plyr)
library(tools)
library(fields)
library(Reumannplatz)
library(shape)
library(devtools)

#which density to use ("dnr" for original estimates, "tom" for your own calculations)
dens.flag<-"dnr"

#what is the earliest year you want? (hunting only: 1960; abundance: 1981; DVC: 1987; Traffic: 1988, Hunters: 1992)
minyear<-1981

#what is the last year you want? (max is 2016)
maxyear<-2016
  
#normalize the data ("norm" for Box-Cox, "detr" for linearly detrend, or "none")
##Code currently work using the "none" option; the normalization steps happen 
##individually with each analysis step (e.g. see line 15 in "DeerAbundance.R" file), 
##because of the conflicting data lengths and dimensions. 
detr.flag<-"none"

#set spatial scale flag for data generation ("usda", "county" or "both")
scale.flag<-"both"

#set directory
setwd("C:/Users/Tom/Documents/GitRepos/mbsync/AndersDeerShort/")
#setwd("/mnt/hgfs/C/Reuman/gitrepos/mbsync/AndersDeerShort/")

#Clean data: end result are two lists of matrices called "cty.list" and "usda.list"
system.time(source("Code/wi.deer.cleandata.R"))
  #list of files generated by wi.deer.cleandata.R:
    #scale.flag == "usda": usda.list, includes data on abundance, kill data, crops, DVCs and traffic
    #scale.flag == "county": cty.list, includes data on abundance, kill data, crops, DVCs and traffic

#calculate how many missing climate values there were (don't need to run anymore)
samplesize.flag<-"n"

system.time(source("Code/wi_climate.R"))
#list of files generated by wi_climate.R:
  #scale.flag == "usda": wsi.usda.mat,hunt.clim.usda, winter.clim.usda,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #scale.flag == "county": wsi.mat,wsi.matN,hunt.clim,winter.clim,nao.mat,pdo.mat,mei.mat,winter.nao,winter.pdo,winter.mei
  #large climate indices are the same values (nao,mei,pdo), just replicated into different dimensions to match scale.flag

#set number of surrogates to use for spatial coherence
nsurrogs<-1000

#Run analysis on deer abundance and DVCs using county data
system.time(source("Code/DeerAbundance.R"))

#Run analysis on deer abundance and DVCs using USDA district data
system.time(source("Code/DeerAbundanceUSDA.R"))

#generate raw data plots
system.time(source("Code/deer_plots.R"))

